PACKAGE_NAME="mundo"
PACKAGE_VERSION="0.1.0"
MAKE[0]="make KERNEL_RELEASE=${kernelver}"
CLEAN="make clean KERNEL_RELEASE=${kernelver}"
BUILT_MODULE_NAME[0]="mundo"
DEST_MODULE_LOCATION[0]="/kernel/net/ipv4"
AUTOINSTALL="yes"
